version: '3'

services:
  backend:
    build: .
    command: npm run dev
    tty: true
    volumes:
      # Mount the source code to enable live reload
      - ./backend/src:/usr/src/app/src
      # Mount the database files to make data persistent
      - ./backend/db:/usr/src/app/db
    ports:
      - 9000:9000

